import { useState, useCallback, useEffect } from "react";
import { operationsController } from "../../controllers/user/operationsController";
import { useAuthStore } from "../../app/store/authStore";
import { useUserBatchRefreshStore } from "../../app/store/userBatchRefreshStore";

const normalizeSourcingBatch = (batch: any) => {
  if (!batch || typeof batch !== "object") {
    return batch;
  }

  return {
    ...batch,
    rmStatus: batch.rmStatus ?? batch.status,
  };
};

export const useSubdepartmentBatches = (targetSlug?: string) => {
  const user = useAuthStore((s) => s.user);
  const refreshVersion = useUserBatchRefreshStore((state) => state.version);

  // Dynamically resolve the real subDepartmentId generated by the server for this slug
  // This eliminates hardcoded ID mismatch issues
  const subDepartmentId = user?.allSubDepartments.find(
    (sd) => sd.slugs?.subDept === targetSlug
  )?.subDepartmentId;
  
  const [batches, setBatches] = useState<any[]>([]);
  const [statusCounts, setStatusCounts] = useState<any>({});
  const [loading, setLoading] = useState<boolean>(true);
  
  // Server-side State Matches API Pagination
  const [page, setPage] = useState<number>(0); // MUI is 0-indexed, API is 1-indexed
  const [rowsPerPage, setRowsPerPage] = useState<number>(10);
  const [search, setSearch] = useState<string>("");
  const [debouncedSearch, setDebouncedSearch] = useState<string>("");
  const [statusFilter, setStatusFilter] = useState<string>("All");
  const [totalRecords, setTotalRecords] = useState<number>(0);

  // Debounce search typing
  useEffect(() => {
    const handler = setTimeout(() => {
      setDebouncedSearch(search);
      setPage(0); // reset page on search
    }, 500);
    return () => clearTimeout(handler);
  }, [search]);

  // Handle Fetching
  const fetchBatches = useCallback(async () => {
    if (!subDepartmentId) {
      setLoading(false);
      return;
    }
    setLoading(true);
    try {
      const payload: any = {
         subDepartmentId,
         userId: String(user?.userId || ""), 
         page: page + 1, // Translate back to 1-index for API
         limit: rowsPerPage,
      };

      if (debouncedSearch.trim()) {
         payload.search = debouncedSearch.trim();
      }

      if (statusFilter !== "All") {
         payload.status = [statusFilter];
      }

      const res = await operationsController.fetchSubdepartmentBatches(payload);
      
      if (res?.success && res.data) {
        setBatches((res.data.batches || []).map(normalizeSourcingBatch));
        setStatusCounts(res.data.statusCounts || {});
        setTotalRecords(res.data.pagination?.totalRecords || 0);
      } else {
        setBatches([]);
        setTotalRecords(0);
        setStatusCounts({});
      }

    } catch (error) {
      console.error("Error fetching subdepartment batches:", error);
    } finally {
      setLoading(false);
    }
  }, [subDepartmentId, user?.userId, page, rowsPerPage, debouncedSearch, statusFilter, refreshVersion]);

  useEffect(() => {
    fetchBatches();
  }, [fetchBatches]);

  return {
    batches,
    statusCounts,
    loading,

    // Controls
    page,
    rowsPerPage,
    search,
    statusFilter,
    totalRecords,

    // Actions
    setPage,
    setRowsPerPage,
    setSearch,
    setStatusFilter,
    refreshUserBatches: fetchBatches,
  };
};
